server:
  port: 80
spring:
  application:
    name: HRMS
    
  cloud:
    gateway:
      routes:
      - id: ATTENDANCE-SERVICE
        uri: lb://ATTENDANCE-SERVICE
        predicates:
        - Path=/attendance/**
        
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

logging:
  level:
    root: INFO
  file:
    name: D:\New folder\hrms.log

                
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.50:8761/eureka