server:
  port: 80
spring:
  application:
    name: HRMS
  config:
    import:
    - configserver:http://192.168.1.60:5050

logging:
  level:
    root: INFO
  file:
    name: G:\HRMS_API\HRMS\app.log    